version: '3.9'
services:
  app:
    build: 
      context: .
      target: dev
    command: air
    volumes:
      - ./:/app
    ports:
      - '5000:5000'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: