package articles

var articlesList = []Article{
	{
		ID:          "1",
		Title:       "Article 1",
		Description: "Description 1",
		Content:     "Content 1",
		Tags:        []string{"tag1", "tag2", "tag3"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "polityka", "geopolityka"},
	},
	{
		ID:          "2",
		Title:       "Article 2",
		Description: "Description 2",
		Content:     "Content 2",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "polityka", "kultura"},
	},
	{
		ID:          "3",
		Title:       "Article 3",
		Description: "Description 3",
		Content:     "Content 3",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "polityka", "sport", "ciekawostki"},
	},
	{
		ID:          "4",
		Title:       "Article 4",
		Description: "Description 4",
		Content:     "Content 4",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "rozrywka"},
	},
	{
		ID:          "5",
		Title:       "Article 5",
		Description: "Description 5",
		Content:     "Content 5",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "rozrywka"},
	},
	{
		ID:          "6",
		Title:       "Article 6",
		Description: "Description 6",
		Content:     "Content 6",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "polityka"},
	},
	{
		ID:          "7",
		Title:       "Article 7",
		Description: "Description 7",
		Content:     "Content 7",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "sport"},
	},
	{
		ID:          "8",
		Title:       "Article 8",
		Description: "Description 8",
		Content:     "Content 8",
		Tags:        []string{"tag1", "tag2"},
		Cover:       "https://picsum.photos/seed/picsum/800/400",
		Categories:  []string{"news", "polityka"},
	},
}
